services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - path: .env
        required: false

    environment:
      - PORT=${PORT:-3000}
      - PREFIX=${PREFIX:-.}
      - OWNER_NUMBER=${OWNER_NUMBER:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DASHBOARD_USER=${DASHBOARD_USER:-admin}
      - DASHBOARD_PASS=${DASHBOARD_PASS:-xortlogix}
      - N8N_ENABLED=${N8N_ENABLED:-true}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL:-https://n8n.srv2029678.hstgr.cloud/webhook/whatsapp-incoming}
      - N8N_BOT_SECRET=${N8N_BOT_SECRET:-my-test-secret-123}
      - N8N_TIMEOUT=${N8N_TIMEOUT:-10000}
      - SERVER_IP=${SERVER_IP:-201.18.214.97}

    volumes:
      - ./auth:/app/auth
      - ./downloads:/app/downloads

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whatsapp-bot.rule=Host(`bot.craveycrust.com`)"
      - "traefik.http.routers.whatsapp-bot.entrypoints=websecure"
      - "traefik.http.routers.whatsapp-bot.tls=true"
      - "traefik.http.routers.whatsapp-bot.tls.certresolver=mytlschallenge"
      - "traefik.http.services.whatsapp-bot.loadbalancer.server.port=3000"
      - "traefik.docker.network=n8n_default"

    networks:
      - default
      - n8n_default

    stdin_open: true
    tty: true

networks:
  n8n_default:
    external: true
